# Base scenario settings are those for m=3, experiment endo 1
max_useful_life: 3
max_order_quantity: 20
max_demand: 20
weekday_demand_negbin_n: [3.5, 11.0, 7.2, 11.1, 5.9, 5.5, 2.2]
weekday_demand_negbin_delta: [5.7, 6.9, 6.5, 6.2, 5.8, 3.3, 3.4]
shelf_life_at_arrival_distribution_c_0: [1.0, 0.5]
shelf_life_at_arrival_distribution_c_1: [0.0, 0.0]
variable_order_cost: 0
fixed_order_cost: 10
shortage_cost: 20
wastage_cost: 5
holding_cost: 1
max_steps_in_episode: 365
gamma: 0.95