defaults:
  - _self_
  - scenario_settings: de_moor_perishable_base_settings
  - rollout_wrapper: de_moor_perishable
  - policy: S_policy

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  searchpath:
    # Search paths assume that run_optuna_simopt.py will be run from simopt/
    - file://../scenarios/de_moor_perishable/conf
    - file://../scenarios/hendrix_perishable_one_product/conf
    - file://../scenarios/hendrix_perishable_substitution_two_product/conf
    - file://../scenarios/mirjalili_perishable_platelet/conf

exp_name: de_moor_perishable/m2/exp1 # Default settings correspond to this experiment

param_search:
  sampler:
    _target_: optuna.samplers.GridSampler
  max_parallel_trials: 50
  max_iterations: 100
  num_rollouts: 500
  seed: 10
  search_bounds:
    all_params:
      low: 0
      high: ${scenario_settings.max_order_quantity}

evaluation:
  seed: 78
  num_rollouts: 1000


