defaults:
  - _self_
  - scenario_settings: de_moor_perishable_base_settings
  - vi_runner: de_moor_perishable
  - rollout_wrapper: de_moor_perishable
  - policy: value_iteration_policy

hydra:
  job:
    chdir: True
  run:
    dir: new_outputs/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  searchpath:
      # Search paths assume that run_value_iteration.py will be run from value_iteration/
    - file://../scenarios/de_moor_perishable/conf
    - file://../scenarios/hendrix_perishable_one_product/conf
    - file://../scenarios/hendrix_perishable_substitution_two_product/conf
    - file://../scenarios/mirjalili_perishable_platelet/conf
    - file://../scenarios/rajendran_perishable_platelet/conf

exp_name: de_moor_perishable/m2/exp1 # Default settings correspond to this experiment

run_settings:
    max_iter: 5000
    min_iter: 1
    extract_policy: True

jax_settings:
  double_precision: True

evaluation:
  perform_eval: True
  seed: 78
  num_rollouts: 10000