_target_: viso_jax.scenarios.rajendran_perishable_platelet.vi_runner.RajendranPerishablePlateletVIR
max_demand: ${scenario_settings.max_demand}
weekday_demand_poisson_mean: ${scenario_settings.weekday_demand_poisson_mean}
max_useful_life: ${scenario_settings.max_useful_life}
max_order_quantity: ${scenario_settings.max_order_quantity}
variable_order_cost: ${scenario_settings.variable_order_cost}
fixed_order_cost: ${scenario_settings.fixed_order_cost}
shortage_cost: ${scenario_settings.shortage_cost}
wastage_cost: ${scenario_settings.wastage_cost}
holding_cost: ${scenario_settings.holding_cost}
max_batch_size: 5000
epsilon: 0.005 
gamma: ${scenario_settings.gamma}
checkpoint_frequency: 1  # Zero for no checkpoints
resume_from_checkpoint: False
periodic_convergence_check: True