_target_: viso_jax.utils.rollout.RolloutWrapper
env_id: DeMoorPerishable
num_env_steps: ${scenario_settings.max_steps_in_episode}
num_burnin_steps: 100
env_kwargs:
  max_useful_life: ${scenario_settings.max_useful_life}
  lead_time: ${scenario_settings.lead_time}
  max_order_quantity: ${scenario_settings.max_order_quantity}
  issue_policy: ${scenario_settings.issue_policy}
env_params:
  max_demand: ${scenario_settings.max_demand}
  demand_gamma_mean: ${scenario_settings.demand_gamma_mean}
  demand_gamma_cov: ${scenario_settings.demand_gamma_cov}
  variable_order_cost: ${scenario_settings.variable_order_cost}
  shortage_cost: ${scenario_settings.shortage_cost}
  wastage_cost: ${scenario_settings.wastage_cost}
  holding_cost: ${scenario_settings.holding_cost}
  max_steps_in_episode: ${scenario_settings.max_steps_in_episode}
  gamma: ${scenario_settings.gamma}
return_info: False