_target_: viso_jax.scenarios.hendrix_perishable_one_product.vi_runner.HendrixPerishableOneProductVIR
max_useful_life: ${scenario_settings.max_useful_life}
max_order_quantity: ${scenario_settings.max_order_quantity}
demand_poisson_mean: ${scenario_settings.demand_poisson_mean}
variable_order_cost: ${scenario_settings.variable_order_cost}
sales_price: ${scenario_settings.sales_price}
max_batch_size: 10000
epsilon: 1e-4
gamma: ${scenario_settings.gamma}
checkpoint_frequency: 1  # Zero for no checkpoints
resume_from_checkpoint: False
use_pmap: True